const exampleService = () => {
  try {
    //aqui se hace la logica de la funcion
  } catch (error) {
    console.error("Error en exampleService:", error);
  }
};

export { exampleService };
